version: "3.9"
services:
  postgres:
    image: postgres
    container_name: ror_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 102030br
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pgconf:/docker-entrypoint-initdb.d/


  # elasticsearch:
  #   container_name: showbiz_elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"


  # redis:
  #   image: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

volumes:
  postgres-data:
  redis-data: